apiVersion: v1
kind: Pod
metadata:
  name: c
  labels:
    app: c
spec:
  containers:
    - name: c
      image: acejilam/centos:7-x86
      command:
        - sleep
        - 1d
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
